services:
  - type: web
    name: music
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn music.wsgi:application --chdir music"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music.settings
      - key: PYTHON_VERSION
        value: 3.10.0
