services:
  - type: web
    name: music-downloader
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn music.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: music.settings
      - key: PYTHON_VERSION
        value: 3.10.0
